### ISSUE TITLE
error code

### ISSUE THREAD

**Issue by digitongithub** [leonardosposina/arduino-led-dot-matrix-clock#3] opened 2023-02-16 16:45 UTC
Compilation error: no matching function for call to 'DS3231::DS3231(const uint8_t&, const uint8_t&)'

what is wrong?

**Comment by leonardosposina** [comment] 2023-02-17 03:14
> Compilation error: no matching function for call to 'DS3231::DS3231(const uint8_t&, const uint8_t&)'
> 
> what is wrong?

Hi, could you please confirm that you have imported the project folder with all the files to your IDE before trying to compile the code?

It seams like you have missing dependencies...

**Comment by digitongithub** [comment] 2023-02-17 07:21
I don't know what happened , but after rebuilding I suddenly get this message :avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x26
Failed uploading: uploading error: exit status 1

I have tried 2 different nano
The compile gives no errors

**Comment by leonardosposina** [comment] 2023-02-17 16:16
> I don't know what happened , but after rebuilding I suddenly get this message :avrdude: stk500_recv(): programmer is not responding
> avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x26
> Failed uploading: uploading error: exit status 1
> 
> I have tried 2 different nano
> The compile gives no errors
> 

This is caused by a connection error between your computer and the Arduino.

You can easily find instructions on how to get this problem sorted by searching the very same log message on Google.

Closing this issue as it is not related to the project...

**Closed** 2023-02-17 16:17 UTC

**Comment by digitongithub** [comment] 2023-02-17 20:35
Thanx for the reaction.
I tried everything, but the nano is not working. My Uno and other are working correct.
After the weekend i try a other computer.
Have a nice weekend.

With regard ton

**Comment by digitongithub** [comment] 2023-02-19 08:55
Found the problem. The seller sold me 2 old nano. Have looked up and implemented a boatloader program. Now the clock works perfectly. Thanks for your comment.

**Comment by digitongithub** [comment] 2023-02-19 09:02
Last question. How i set the date and time. Is now wrong (year 2000 and different time)
